language: php

services:
  - mysql

before_script:
  - echo "[mysql]\nhost = localhost\nuser = root\npassword = \n" > amisstestrc

php:
  - "nightly"
  - "hhvm"
  - 8.1
  - 8.0
  - 7.4
  - 5.6

branches:
  only:
    - master
    - develop

script: php test/run.php --with-mysql --exclude-group=faulty,faulty-sqlite,faulty-mysql

matrix:
  allowed_failures:
    - php: 5.5
    - php: 5.4

